package dev.rendrap.app.movienight.core.resource.strings

import cafe.adriel.lyricist.LyricistStrings
import dev.rendrap.app.movienight.core.common.utils.Locales

@LyricistStrings(languageTag = Locales.EN_US, default = true)
internal val EnUsStrings = Strings(
    movies = "Movies",
    tvSeries = "TV Series",
    popularNow = "Popular Now",
    nowPlaying = "Now Playing",
    topRated = "Top Rated",
    upcoming = "Upcoming",
    trending = "Trending",
    favorite = "Favorites",
    discover = "Discover",
    catalog = "Catalog",
    setting = "Settings",
    readMore = "Read More",
    play = "Play",
    trailerAndTeaser = "Trailer & Teaser",
    seasonAndEpisode = "Season & Episode",
    ratingAndReview = "Rating & Review",
    castAndCrew = "Cast & Crew",
    youMayAlsoLike = "You May also Like",
    filmography = "Filmography",
    dateOfBirth = "Date of Birth",
    placeOfBirth = "Place of Birth",
    addToLibrary = "Add to Library",
    add = "Add",
    filters = "Filters",
    search = "Search",
    genre = "Genre",
    genres = "Genres",
    country = "Country",
    year = "Year",
    language = "Language",
    rating = "Rating",
    sortBy = "Sort By",
    apply = "Apply",
    reset = "Reset",
    share = "Share",
    noResultTitle = "No Results",
    noResultDescription = { keyword ->
        "There were no results fot \"$keyword\". Try a new search."
    },
    library = "Library",
    myPlaylists = "My Playlists",
    rename = "Rename",
    deletePlaylist = "Delete Playlist",
    theme = "Theme",
    deleteCache = "Delete Cache",
    deleteData = "Delete Data",
    selectAvatar = "Select Avatar",
    editProfile = "Edit Profile",
    profileName = "Profile Name",
    saveChanges = "Save Changes",
    takeAPhoto = "Take a Photo",
    chooseFromGallery = "Choose From Gallery",
    noInternetConnection = "⚠\uFE0F You aren’t connected to the internet",
    airingToday = "Airing Today",
    onTheAir = "On the Air",
)