package dev.rendrap.app.movienight.core.resource.strings

import cafe.adriel.lyricist.LyricistStrings
import dev.rendrap.app.movienight.core.common.utils.Locales

@LyricistStrings(languageTag = Locales.IN_ID)
internal val InIdStrings = Strings(
    movies = "Film",
    tvSeries = "Seri TV",
    popularNow = "Populer Sekarang",
    nowPlaying = "Sedang Tayang",
    topRated = "Rating Tertinggi",
    upcoming = "Akan Datang",
    trending = "Tren",
    favorite = "Favorit",
    discover = "Temukan",
    catalog = "Katalog",
    setting = "Pengaturan",
    readMore = "Lebih Banyak",
    play = "Main",
    trailerAndTeaser = "Trailer & Teaser",
    seasonAndEpisode = "Season & Episode",
    ratingAndReview = "Rating & Ulasan",
    castAndCrew = "Pemain & Kru",
    youMayAlsoLike = "Kamu Mungkin Juga Suka",
    filmography = "Filmografi",
    dateOfBirth = "Tanggal Lahir",
    placeOfBirth = "Tempat Lahir",
    addToLibrary = "Tambah ke Library",
    add = "Tambah",
    filters = "Filter",
    search = "Cari",
    genre = "Genre",
    genres = "Genres",
    country = "Negara",
    year = "Tahun",
    language = "Bahasa",
    rating = "Rating",
    sortBy = "Sortir",
    apply = "Terapkah",
    reset = "Reset",
    share = "Bagikan",
    noResultTitle = "Tidak Ada Hasil",
    noResultDescription = { keyword ->
        "Tidak ada hasil untuk \"$keyword\". Coba pencarian baru."
    },
    library = "Library",
    myPlaylists = "Daftar Putar Saya",
    rename = "Ganti Name",
    deletePlaylist = "Hapus Daftar Putar",
    theme = "Tema",
    deleteCache = "Hapus Cache",
    deleteData = "Hapus Data",
    selectAvatar = "Pilih Avatar",
    editProfile = "Ubah Profil",
    profileName = "Nama Profil",
    saveChanges = "Simpan Perubahan",
    takeAPhoto = "Ambil Foto",
    chooseFromGallery = "Pilih dari Galeri",
)